version: '3.4'

services:
  demo-rabbit:
        build:
            context: ./rabbitmq
            dockerfile: ./Dockerfile.rabbitmq
        ports:
            - 5672:5672
            - 15672:15672